import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { SubHubShell } from "@/components/erp/SubHubShell";
import { Panel, Tag } from "@/components/erp/bits";
import { getBatchDetailFn } from "@/inventory";
import type { BatchLineage, BatchMovement, InventoryBatch, QualityLog } from "@/inventory.server";
import { num } from "@/lib/erp-data";

export const Route = createFileRoute("/inventory/batches/$batchId")({ component: BatchDetailPage });

type Detail = { batch: InventoryBatch; movements: BatchMovement[]; parents: BatchLineage[]; children: BatchLineage[]; qualityLogs: QualityLog[] };

function BatchDetailPage() {
  const { batchId } = Route.useParams();
  const [data, setData] = useState<Detail | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void getBatchDetailFn({ data: { batchId } }).then((result) => result.ok ? setData(result as Detail) : setError(result.message)); }, [batchId]);
  return <SubHubShell actions={<Link to="/inventory/batches" className="text-sm text-primary hover:underline">Back to batch register</Link>}><section className="space-y-6 p-6">{error ? <p role="alert" className="rounded-md border border-destructive/25 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</p> : null}{!data ? <p className="text-sm text-muted-foreground">Loading batch traceability…</p> : <><Panel title="Batch traceability" description={`${data.batch.itemName} · ${data.batch.itemCode}`}><div className="flex flex-wrap items-start justify-between gap-4 border-b border-border p-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Batch code</p><h1 className="tabular mt-1 text-xl font-semibold">{data.batch.batchCode}</h1></div><Tag tone={data.batch.availableQuantity ? "good" : "warn"}>{data.batch.status}</Tag></div><dl className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4">{[["Category", data.batch.category], ["Source", data.batch.source], ["Source reference", data.batch.sourceReference], ["Logged", formatDate(data.batch.loggedAt)], ["Received", num(data.batch.receivedQuantity)], ["Produced", num(data.batch.producedQuantity)], ["Consumed", num(data.batch.consumedQuantity)], ["Defective", num(data.batch.defectiveQuantity)], ["Available", num(data.batch.availableQuantity)]].map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm font-medium">{value}</dd></div>)}</dl><div className="border-t border-border p-5"><h2 className="text-sm font-semibold">Source metadata</h2><dl className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(data.batch.sourceMetadata).length ? Object.entries(data.batch.sourceMetadata).map(([key, value]) => <div key={key} className="rounded border border-border/70 bg-muted/20 px-3 py-2"><dt className="text-xs text-muted-foreground">{labelize(key)}</dt><dd className="mt-1 break-words text-sm">{value}</dd></div>) : <p className="text-sm text-muted-foreground">No additional source metadata recorded.</p>}</dl></div></Panel><Lineage title="Parent input batches" rows={data.parents} parent /><Lineage title="Child output batches" rows={data.children} /><QualityTable logs={data.qualityLogs} /><Ledger movements={data.movements} /></>}</section></SubHubShell>;
}

function formatDate(value: string) { return value.replace("T", " ").slice(0, 19); }
function labelize(value: string) { return value.replace(/([A-Z])/g, " $1").replace(/[_-]/g, " ").replace(/^./, (char) => char.toUpperCase()); }

function Ledger({ movements }: { movements: BatchMovement[] }) {
  return <Panel title="Movement ledger" description="Append-only events recorded against this batch.">{movements.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b border-border text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">Date / time</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Actor</th><th className="px-5 py-3">Reason / reference</th><th className="px-5 py-3 text-right">Delta</th><th className="px-5 py-3 text-right">Balance</th></tr></thead><tbody>{movements.map((movement) => <tr key={movement.id} className="border-b border-border/70"><td className="tabular whitespace-nowrap px-5 py-3 text-xs">{formatDate(movement.createdAt)}</td><td className="px-5 py-3">{movement.type}</td><td className="px-5 py-3">{movement.actor}</td><td className="px-5 py-3"><p>{movement.reason}</p><p className="text-xs text-muted-foreground">{movement.reference}</p></td><td className={`tabular px-5 py-3 text-right font-semibold ${movement.quantityDelta > 0 ? "text-success" : "text-destructive"}`}>{movement.quantityDelta > 0 ? "+" : ""}{movement.quantityDelta}</td><td className="tabular px-5 py-3 text-right">{num(movement.balance)}</td></tr>)}</tbody></table></div> : <p className="p-5 text-sm text-muted-foreground">No movements recorded.</p>}</Panel>;
}

function QualityTable({ logs }: { logs: QualityLog[] }) {
  return <Panel title="Quality records" description="Quality deductions associated with this inventory workspace.">{logs.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="border-b border-border text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Issue</th><th className="px-5 py-3 text-right">Quantity</th><th className="px-5 py-3">Recorded by</th><th className="px-5 py-3">Notes</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id} className="border-b border-border/70"><td className="tabular px-5 py-3 text-xs">{formatDate(log.date)}</td><td className="px-5 py-3"><Tag tone="bad">{log.issue}</Tag></td><td className="tabular px-5 py-3 text-right text-destructive">-{num(log.quantity)}</td><td className="px-5 py-3">{log.recordedByName || log.recordedBy}</td><td className="px-5 py-3 text-muted-foreground">{log.notes || "—"}</td></tr>)}</tbody></table></div> : <p className="p-5 text-sm text-muted-foreground">No quality records linked to this batch.</p>}</Panel>;
}

function Lineage({ title, rows, parent }: { title: string; rows: BatchLineage[]; parent?: boolean }) {
  return <Panel title={title} description={parent ? "Inputs consumed to create this batch." : "Outputs created from this batch."}>{rows.length ? <ul className="divide-y divide-border">{rows.map((row) => { const id = parent ? row.parentBatchId : row.childBatchId; const code = parent ? row.parentBatchCode : row.childBatchCode; const itemCode = parent ? row.parentItemCode : row.childItemCode; const itemName = parent ? row.parentItemName : row.childItemName; return <li key={row.id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-3 text-sm"><div><Link to="/inventory/batches/$batchId" params={{ batchId: id }} className="font-medium text-primary hover:underline">{code}</Link><p className="text-xs text-muted-foreground">{itemName} · {itemCode}</p></div><div className="text-right"><p className="tabular font-medium">{num(row.quantity)} units</p><p className="text-xs text-muted-foreground">{row.reference} · {formatDate(row.createdAt)}</p></div></li>; })}</ul> : <p className="p-5 text-sm text-muted-foreground">No linked batches.</p>}</Panel>;
}