// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/procurement-orders/Current.tsx": () => import("../components/mockups/procurement-orders/Current.tsx"),
  "./components/mockups/procurement-orders/Refreshed.tsx": () => import("../components/mockups/procurement-orders/Refreshed.tsx")
};
