/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BomRouteImport } from './routes/bom'
import { Route as HrRouteImport } from './routes/hr'
import { Route as HubsRouteImport } from './routes/hubs'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ProductionTargetsRouteImport } from './routes/production-targets'
import { Route as QualityManagementRouteImport } from './routes/quality-management'
import { Route as RawMaterialsRouteImport } from './routes/raw-materials'
import { Route as ShortagesRouteImport } from './routes/shortages'
import { Route as SubhubRouteImport } from './routes/subhub'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BomCodeRouteImport } from './routes/bom.$code'
import { Route as HubCodeRouteImport } from './routes/hub.$code'
import { Route as HubsHubIdRouteImport } from './routes/hubs.$hubId'
import { Route as InventoryBatchesRouteImport } from './routes/inventory.batches'
import { Route as InventoryFinalProductsRouteImport } from './routes/inventory.final-products'
import { Route as InventoryHistoryRouteImport } from './routes/inventory.history'
import { Route as InventoryQualityRouteImport } from './routes/inventory.quality'
import { Route as InventoryRawMaterialsRouteImport } from './routes/inventory.raw-materials'
import { Route as PartCodeRouteImport } from './routes/part.$code'
import { Route as PoIdRouteImport } from './routes/po.$id'
import { Route as SkuCodeRouteImport } from './routes/sku.$code'
import { Route as SubhubBomRouteImport } from './routes/subhub.bom'
import { Route as SubhubFloatParentRouteImport } from './routes/subhub.float-parent'
import { Route as SubhubHrRouteImport } from './routes/subhub.hr'
import { Route as SubhubProductionRouteImport } from './routes/subhub.production'
import { Route as SubhubRawMaterialsRouteImport } from './routes/subhub.raw-materials'
import { Route as SubhubReportsRouteImport } from './routes/subhub.reports'
import { Route as WorkerIdRouteImport } from './routes/worker.$id'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as InventoryBatchesBatchIdRouteImport } from './routes/inventory.batches.$batchId'
import { Route as InventoryItemsItemCodeRouteImport } from './routes/inventory.items.$itemCode'
import { Route as SubhubBomCodeRouteImport } from './routes/subhub.bom.$code'
import { Route as SubhubParentCodeRouteImport } from './routes/subhub.parent.$code'
import { Route as HrEmployeeSubhubIdEmployeeIdRouteImport } from './routes/hr.employee.$subhubId.$employeeId'
import { Route as SubhubHrEmployeeEmployeeIdRouteImport } from './routes/subhub.hr.employee.$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BomRoute = BomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsRoute = HubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionTargetsRoute = ProductionTargetsRouteImport.update({
  id: '/production-targets',
  path: '/production-targets',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityManagementRoute = QualityManagementRouteImport.update({
  id: '/quality-management',
  path: '/quality-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RawMaterialsRoute = RawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortagesRoute = ShortagesRouteImport.update({
  id: '/shortages',
  path: '/shortages',
  getParentRoute: () => rootRouteImport,
} as any)
const SubhubRoute = SubhubRouteImport.update({
  id: '/subhub',
  path: '/subhub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BomCodeRoute = BomCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => BomRoute,
} as any)
const HubCodeRoute = HubCodeRouteImport.update({
  id: '/hub/$code',
  path: '/hub/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsHubIdRoute = HubsHubIdRouteImport.update({
  id: '/$hubId',
  path: '/$hubId',
  getParentRoute: () => HubsRoute,
} as any)
const InventoryBatchesRoute = InventoryBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryFinalProductsRoute = InventoryFinalProductsRouteImport.update({
  id: '/final-products',
  path: '/final-products',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryHistoryRoute = InventoryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryQualityRoute = InventoryQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryRawMaterialsRoute = InventoryRawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => InventoryRoute,
} as any)
const PartCodeRoute = PartCodeRouteImport.update({
  id: '/part/$code',
  path: '/part/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PoIdRoute = PoIdRouteImport.update({
  id: '/po/$id',
  path: '/po/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkuCodeRoute = SkuCodeRouteImport.update({
  id: '/sku/$code',
  path: '/sku/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SubhubBomRoute = SubhubBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubFloatParentRoute = SubhubFloatParentRouteImport.update({
  id: '/float-parent',
  path: '/float-parent',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubHrRoute = SubhubHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubProductionRoute = SubhubProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubRawMaterialsRoute = SubhubRawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubReportsRoute = SubhubReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SubhubRoute,
} as any)
const WorkerIdRoute = WorkerIdRouteImport.update({
  id: '/worker/$id',
  path: '/worker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const InventoryBatchesBatchIdRoute = InventoryBatchesBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => InventoryBatchesRoute,
} as any)
const InventoryItemsItemCodeRoute = InventoryItemsItemCodeRouteImport.update({
  id: '/items/$itemCode',
  path: '/items/$itemCode',
  getParentRoute: () => InventoryRoute,
} as any)
const SubhubBomCodeRoute = SubhubBomCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => SubhubBomRoute,
} as any)
const SubhubParentCodeRoute = SubhubParentCodeRouteImport.update({
  id: '/parent/$code',
  path: '/parent/$code',
  getParentRoute: () => SubhubRoute,
} as any)
const HrEmployeeSubhubIdEmployeeIdRoute =
  HrEmployeeSubhubIdEmployeeIdRouteImport.update({
    id: '/employee/$subhubId/$employeeId',
    path: '/employee/$subhubId/$employeeId',
    getParentRoute: () => HrRoute,
  } as any)
const SubhubHrEmployeeEmployeeIdRoute =
  SubhubHrEmployeeEmployeeIdRouteImport.update({
    id: '/employee/$employeeId',
    path: '/employee/$employeeId',
    getParentRoute: () => SubhubHrRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bom': typeof BomRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/hubs': typeof HubsRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/production-targets': typeof ProductionTargetsRoute
  '/quality-management': typeof QualityManagementRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/shortages': typeof ShortagesRoute
  '/subhub': typeof SubhubRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/bom/$code': typeof BomCodeRoute
  '/hub/$code': typeof HubCodeRoute
  '/hubs/$hubId': typeof HubsHubIdRoute
  '/inventory/batches': typeof InventoryBatchesRouteWithChildren
  '/inventory/final-products': typeof InventoryFinalProductsRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/quality': typeof InventoryQualityRoute
  '/inventory/raw-materials': typeof InventoryRawMaterialsRoute
  '/part/$code': typeof PartCodeRoute
  '/po/$id': typeof PoIdRoute
  '/sku/$code': typeof SkuCodeRoute
  '/subhub/bom': typeof SubhubBomRouteWithChildren
  '/subhub/float-parent': typeof SubhubFloatParentRoute
  '/subhub/hr': typeof SubhubHrRouteWithChildren
  '/subhub/production': typeof SubhubProductionRoute
  '/subhub/raw-materials': typeof SubhubRawMaterialsRoute
  '/subhub/reports': typeof SubhubReportsRoute
  '/worker/$id': typeof WorkerIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/inventory/batches/$batchId': typeof InventoryBatchesBatchIdRoute
  '/inventory/items/$itemCode': typeof InventoryItemsItemCodeRoute
  '/subhub/bom/$code': typeof SubhubBomCodeRoute
  '/subhub/parent/$code': typeof SubhubParentCodeRoute
  '/hr/employee/$subhubId/$employeeId': typeof HrEmployeeSubhubIdEmployeeIdRoute
  '/subhub/hr/employee/$employeeId': typeof SubhubHrEmployeeEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bom': typeof BomRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/hubs': typeof HubsRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/production-targets': typeof ProductionTargetsRoute
  '/quality-management': typeof QualityManagementRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/shortages': typeof ShortagesRoute
  '/subhub': typeof SubhubRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/bom/$code': typeof BomCodeRoute
  '/hub/$code': typeof HubCodeRoute
  '/hubs/$hubId': typeof HubsHubIdRoute
  '/inventory/batches': typeof InventoryBatchesRouteWithChildren
  '/inventory/final-products': typeof InventoryFinalProductsRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/quality': typeof InventoryQualityRoute
  '/inventory/raw-materials': typeof InventoryRawMaterialsRoute
  '/part/$code': typeof PartCodeRoute
  '/po/$id': typeof PoIdRoute
  '/sku/$code': typeof SkuCodeRoute
  '/subhub/bom': typeof SubhubBomRouteWithChildren
  '/subhub/float-parent': typeof SubhubFloatParentRoute
  '/subhub/hr': typeof SubhubHrRouteWithChildren
  '/subhub/production': typeof SubhubProductionRoute
  '/subhub/raw-materials': typeof SubhubRawMaterialsRoute
  '/subhub/reports': typeof SubhubReportsRoute
  '/worker/$id': typeof WorkerIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/inventory/batches/$batchId': typeof InventoryBatchesBatchIdRoute
  '/inventory/items/$itemCode': typeof InventoryItemsItemCodeRoute
  '/subhub/bom/$code': typeof SubhubBomCodeRoute
  '/subhub/parent/$code': typeof SubhubParentCodeRoute
  '/hr/employee/$subhubId/$employeeId': typeof HrEmployeeSubhubIdEmployeeIdRoute
  '/subhub/hr/employee/$employeeId': typeof SubhubHrEmployeeEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bom': typeof BomRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/hubs': typeof HubsRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/production-targets': typeof ProductionTargetsRoute
  '/quality-management': typeof QualityManagementRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/shortages': typeof ShortagesRoute
  '/subhub': typeof SubhubRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/bom/$code': typeof BomCodeRoute
  '/hub/$code': typeof HubCodeRoute
  '/hubs/$hubId': typeof HubsHubIdRoute
  '/inventory/batches': typeof InventoryBatchesRouteWithChildren
  '/inventory/final-products': typeof InventoryFinalProductsRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/quality': typeof InventoryQualityRoute
  '/inventory/raw-materials': typeof InventoryRawMaterialsRoute
  '/part/$code': typeof PartCodeRoute
  '/po/$id': typeof PoIdRoute
  '/sku/$code': typeof SkuCodeRoute
  '/subhub/bom': typeof SubhubBomRouteWithChildren
  '/subhub/float-parent': typeof SubhubFloatParentRoute
  '/subhub/hr': typeof SubhubHrRouteWithChildren
  '/subhub/production': typeof SubhubProductionRoute
  '/subhub/raw-materials': typeof SubhubRawMaterialsRoute
  '/subhub/reports': typeof SubhubReportsRoute
  '/worker/$id': typeof WorkerIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/inventory/batches/$batchId': typeof InventoryBatchesBatchIdRoute
  '/inventory/items/$itemCode': typeof InventoryItemsItemCodeRoute
  '/subhub/bom/$code': typeof SubhubBomCodeRoute
  '/subhub/parent/$code': typeof SubhubParentCodeRoute
  '/hr/employee/$subhubId/$employeeId': typeof HrEmployeeSubhubIdEmployeeIdRoute
  '/subhub/hr/employee/$employeeId': typeof SubhubHrEmployeeEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bom'
    | '/hr'
    | '/hubs'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/production'
    | '/production-targets'
    | '/quality-management'
    | '/raw-materials'
    | '/shortages'
    | '/subhub'
    | '/admin/users'
    | '/bom/$code'
    | '/hub/$code'
    | '/hubs/$hubId'
    | '/inventory/batches'
    | '/inventory/final-products'
    | '/inventory/history'
    | '/inventory/quality'
    | '/inventory/raw-materials'
    | '/part/$code'
    | '/po/$id'
    | '/sku/$code'
    | '/subhub/bom'
    | '/subhub/float-parent'
    | '/subhub/hr'
    | '/subhub/production'
    | '/subhub/raw-materials'
    | '/subhub/reports'
    | '/worker/$id'
    | '/admin/users/$userId'
    | '/inventory/batches/$batchId'
    | '/inventory/items/$itemCode'
    | '/subhub/bom/$code'
    | '/subhub/parent/$code'
    | '/hr/employee/$subhubId/$employeeId'
    | '/subhub/hr/employee/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bom'
    | '/hr'
    | '/hubs'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/production'
    | '/production-targets'
    | '/quality-management'
    | '/raw-materials'
    | '/shortages'
    | '/subhub'
    | '/admin/users'
    | '/bom/$code'
    | '/hub/$code'
    | '/hubs/$hubId'
    | '/inventory/batches'
    | '/inventory/final-products'
    | '/inventory/history'
    | '/inventory/quality'
    | '/inventory/raw-materials'
    | '/part/$code'
    | '/po/$id'
    | '/sku/$code'
    | '/subhub/bom'
    | '/subhub/float-parent'
    | '/subhub/hr'
    | '/subhub/production'
    | '/subhub/raw-materials'
    | '/subhub/reports'
    | '/worker/$id'
    | '/admin/users/$userId'
    | '/inventory/batches/$batchId'
    | '/inventory/items/$itemCode'
    | '/subhub/bom/$code'
    | '/subhub/parent/$code'
    | '/hr/employee/$subhubId/$employeeId'
    | '/subhub/hr/employee/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/bom'
    | '/hr'
    | '/hubs'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/production'
    | '/production-targets'
    | '/quality-management'
    | '/raw-materials'
    | '/shortages'
    | '/subhub'
    | '/admin/users'
    | '/bom/$code'
    | '/hub/$code'
    | '/hubs/$hubId'
    | '/inventory/batches'
    | '/inventory/final-products'
    | '/inventory/history'
    | '/inventory/quality'
    | '/inventory/raw-materials'
    | '/part/$code'
    | '/po/$id'
    | '/sku/$code'
    | '/subhub/bom'
    | '/subhub/float-parent'
    | '/subhub/hr'
    | '/subhub/production'
    | '/subhub/raw-materials'
    | '/subhub/reports'
    | '/worker/$id'
    | '/admin/users/$userId'
    | '/inventory/batches/$batchId'
    | '/inventory/items/$itemCode'
    | '/subhub/bom/$code'
    | '/subhub/parent/$code'
    | '/hr/employee/$subhubId/$employeeId'
    | '/subhub/hr/employee/$employeeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BomRoute: typeof BomRouteWithChildren
  HrRoute: typeof HrRouteWithChildren
  HubsRoute: typeof HubsRouteWithChildren
  InventoryRoute: typeof InventoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProcurementRoute: typeof ProcurementRoute
  ProductionRoute: typeof ProductionRoute
  ProductionTargetsRoute: typeof ProductionTargetsRoute
  QualityManagementRoute: typeof QualityManagementRoute
  RawMaterialsRoute: typeof RawMaterialsRoute
  ShortagesRoute: typeof ShortagesRoute
  SubhubRoute: typeof SubhubRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  HubCodeRoute: typeof HubCodeRoute
  PartCodeRoute: typeof PartCodeRoute
  PoIdRoute: typeof PoIdRoute
  SkuCodeRoute: typeof SkuCodeRoute
  WorkerIdRoute: typeof WorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom': {
      id: '/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof BomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs': {
      id: '/hubs'
      path: '/hubs'
      fullPath: '/hubs'
      preLoaderRoute: typeof HubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-targets': {
      id: '/production-targets'
      path: '/production-targets'
      fullPath: '/production-targets'
      preLoaderRoute: typeof ProductionTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-management': {
      id: '/quality-management'
      path: '/quality-management'
      fullPath: '/quality-management'
      preLoaderRoute: typeof QualityManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-materials': {
      id: '/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof RawMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortages': {
      id: '/shortages'
      path: '/shortages'
      fullPath: '/shortages'
      preLoaderRoute: typeof ShortagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subhub': {
      id: '/subhub'
      path: '/subhub'
      fullPath: '/subhub'
      preLoaderRoute: typeof SubhubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom/$code': {
      id: '/bom/$code'
      path: '/$code'
      fullPath: '/bom/$code'
      preLoaderRoute: typeof BomCodeRouteImport
      parentRoute: typeof BomRoute
    }
    '/hub/$code': {
      id: '/hub/$code'
      path: '/hub/$code'
      fullPath: '/hub/$code'
      preLoaderRoute: typeof HubCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs/$hubId': {
      id: '/hubs/$hubId'
      path: '/$hubId'
      fullPath: '/hubs/$hubId'
      preLoaderRoute: typeof HubsHubIdRouteImport
      parentRoute: typeof HubsRoute
    }
    '/inventory/batches': {
      id: '/inventory/batches'
      path: '/batches'
      fullPath: '/inventory/batches'
      preLoaderRoute: typeof InventoryBatchesRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/final-products': {
      id: '/inventory/final-products'
      path: '/final-products'
      fullPath: '/inventory/final-products'
      preLoaderRoute: typeof InventoryFinalProductsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/history': {
      id: '/inventory/history'
      path: '/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof InventoryHistoryRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/quality': {
      id: '/inventory/quality'
      path: '/quality'
      fullPath: '/inventory/quality'
      preLoaderRoute: typeof InventoryQualityRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/raw-materials': {
      id: '/inventory/raw-materials'
      path: '/raw-materials'
      fullPath: '/inventory/raw-materials'
      preLoaderRoute: typeof InventoryRawMaterialsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/part/$code': {
      id: '/part/$code'
      path: '/part/$code'
      fullPath: '/part/$code'
      preLoaderRoute: typeof PartCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/$id': {
      id: '/po/$id'
      path: '/po/$id'
      fullPath: '/po/$id'
      preLoaderRoute: typeof PoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sku/$code': {
      id: '/sku/$code'
      path: '/sku/$code'
      fullPath: '/sku/$code'
      preLoaderRoute: typeof SkuCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subhub/bom': {
      id: '/subhub/bom'
      path: '/bom'
      fullPath: '/subhub/bom'
      preLoaderRoute: typeof SubhubBomRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/float-parent': {
      id: '/subhub/float-parent'
      path: '/float-parent'
      fullPath: '/subhub/float-parent'
      preLoaderRoute: typeof SubhubFloatParentRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/hr': {
      id: '/subhub/hr'
      path: '/hr'
      fullPath: '/subhub/hr'
      preLoaderRoute: typeof SubhubHrRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/production': {
      id: '/subhub/production'
      path: '/production'
      fullPath: '/subhub/production'
      preLoaderRoute: typeof SubhubProductionRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/raw-materials': {
      id: '/subhub/raw-materials'
      path: '/raw-materials'
      fullPath: '/subhub/raw-materials'
      preLoaderRoute: typeof SubhubRawMaterialsRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/reports': {
      id: '/subhub/reports'
      path: '/reports'
      fullPath: '/subhub/reports'
      preLoaderRoute: typeof SubhubReportsRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/worker/$id': {
      id: '/worker/$id'
      path: '/worker/$id'
      fullPath: '/worker/$id'
      preLoaderRoute: typeof WorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/inventory/batches/$batchId': {
      id: '/inventory/batches/$batchId'
      path: '/$batchId'
      fullPath: '/inventory/batches/$batchId'
      preLoaderRoute: typeof InventoryBatchesBatchIdRouteImport
      parentRoute: typeof InventoryBatchesRoute
    }
    '/inventory/items/$itemCode': {
      id: '/inventory/items/$itemCode'
      path: '/items/$itemCode'
      fullPath: '/inventory/items/$itemCode'
      preLoaderRoute: typeof InventoryItemsItemCodeRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/subhub/bom/$code': {
      id: '/subhub/bom/$code'
      path: '/$code'
      fullPath: '/subhub/bom/$code'
      preLoaderRoute: typeof SubhubBomCodeRouteImport
      parentRoute: typeof SubhubBomRoute
    }
    '/subhub/parent/$code': {
      id: '/subhub/parent/$code'
      path: '/parent/$code'
      fullPath: '/subhub/parent/$code'
      preLoaderRoute: typeof SubhubParentCodeRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/hr/employee/$subhubId/$employeeId': {
      id: '/hr/employee/$subhubId/$employeeId'
      path: '/employee/$subhubId/$employeeId'
      fullPath: '/hr/employee/$subhubId/$employeeId'
      preLoaderRoute: typeof HrEmployeeSubhubIdEmployeeIdRouteImport
      parentRoute: typeof HrRoute
    }
    '/subhub/hr/employee/$employeeId': {
      id: '/subhub/hr/employee/$employeeId'
      path: '/employee/$employeeId'
      fullPath: '/subhub/hr/employee/$employeeId'
      preLoaderRoute: typeof SubhubHrEmployeeEmployeeIdRouteImport
      parentRoute: typeof SubhubHrRoute
    }
  }
}

interface BomRouteChildren {
  BomCodeRoute: typeof BomCodeRoute
}

const BomRouteChildren: BomRouteChildren = {
  BomCodeRoute: BomCodeRoute,
}

const BomRouteWithChildren = BomRoute._addFileChildren(BomRouteChildren)

interface HrRouteChildren {
  HrEmployeeSubhubIdEmployeeIdRoute: typeof HrEmployeeSubhubIdEmployeeIdRoute
}

const HrRouteChildren: HrRouteChildren = {
  HrEmployeeSubhubIdEmployeeIdRoute: HrEmployeeSubhubIdEmployeeIdRoute,
}

const HrRouteWithChildren = HrRoute._addFileChildren(HrRouteChildren)

interface HubsRouteChildren {
  HubsHubIdRoute: typeof HubsHubIdRoute
}

const HubsRouteChildren: HubsRouteChildren = {
  HubsHubIdRoute: HubsHubIdRoute,
}

const HubsRouteWithChildren = HubsRoute._addFileChildren(HubsRouteChildren)

interface InventoryBatchesRouteChildren {
  InventoryBatchesBatchIdRoute: typeof InventoryBatchesBatchIdRoute
}

const InventoryBatchesRouteChildren: InventoryBatchesRouteChildren = {
  InventoryBatchesBatchIdRoute: InventoryBatchesBatchIdRoute,
}

const InventoryBatchesRouteWithChildren =
  InventoryBatchesRoute._addFileChildren(InventoryBatchesRouteChildren)

interface InventoryRouteChildren {
  InventoryBatchesRoute: typeof InventoryBatchesRouteWithChildren
  InventoryFinalProductsRoute: typeof InventoryFinalProductsRoute
  InventoryHistoryRoute: typeof InventoryHistoryRoute
  InventoryQualityRoute: typeof InventoryQualityRoute
  InventoryRawMaterialsRoute: typeof InventoryRawMaterialsRoute
  InventoryItemsItemCodeRoute: typeof InventoryItemsItemCodeRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryBatchesRoute: InventoryBatchesRouteWithChildren,
  InventoryFinalProductsRoute: InventoryFinalProductsRoute,
  InventoryHistoryRoute: InventoryHistoryRoute,
  InventoryQualityRoute: InventoryQualityRoute,
  InventoryRawMaterialsRoute: InventoryRawMaterialsRoute,
  InventoryItemsItemCodeRoute: InventoryItemsItemCodeRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface SubhubBomRouteChildren {
  SubhubBomCodeRoute: typeof SubhubBomCodeRoute
}

const SubhubBomRouteChildren: SubhubBomRouteChildren = {
  SubhubBomCodeRoute: SubhubBomCodeRoute,
}

const SubhubBomRouteWithChildren = SubhubBomRoute._addFileChildren(
  SubhubBomRouteChildren,
)

interface SubhubHrRouteChildren {
  SubhubHrEmployeeEmployeeIdRoute: typeof SubhubHrEmployeeEmployeeIdRoute
}

const SubhubHrRouteChildren: SubhubHrRouteChildren = {
  SubhubHrEmployeeEmployeeIdRoute: SubhubHrEmployeeEmployeeIdRoute,
}

const SubhubHrRouteWithChildren = SubhubHrRoute._addFileChildren(
  SubhubHrRouteChildren,
)

interface SubhubRouteChildren {
  SubhubBomRoute: typeof SubhubBomRouteWithChildren
  SubhubFloatParentRoute: typeof SubhubFloatParentRoute
  SubhubHrRoute: typeof SubhubHrRouteWithChildren
  SubhubProductionRoute: typeof SubhubProductionRoute
  SubhubRawMaterialsRoute: typeof SubhubRawMaterialsRoute
  SubhubReportsRoute: typeof SubhubReportsRoute
  SubhubParentCodeRoute: typeof SubhubParentCodeRoute
}

const SubhubRouteChildren: SubhubRouteChildren = {
  SubhubBomRoute: SubhubBomRouteWithChildren,
  SubhubFloatParentRoute: SubhubFloatParentRoute,
  SubhubHrRoute: SubhubHrRouteWithChildren,
  SubhubProductionRoute: SubhubProductionRoute,
  SubhubRawMaterialsRoute: SubhubRawMaterialsRoute,
  SubhubReportsRoute: SubhubReportsRoute,
  SubhubParentCodeRoute: SubhubParentCodeRoute,
}

const SubhubRouteWithChildren =
  SubhubRoute._addFileChildren(SubhubRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BomRoute: BomRouteWithChildren,
  HrRoute: HrRouteWithChildren,
  HubsRoute: HubsRouteWithChildren,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProcurementRoute: ProcurementRoute,
  ProductionRoute: ProductionRoute,
  ProductionTargetsRoute: ProductionTargetsRoute,
  QualityManagementRoute: QualityManagementRoute,
  RawMaterialsRoute: RawMaterialsRoute,
  ShortagesRoute: ShortagesRoute,
  SubhubRoute: SubhubRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  HubCodeRoute: HubCodeRoute,
  PartCodeRoute: PartCodeRoute,
  PoIdRoute: PoIdRoute,
  SkuCodeRoute: SkuCodeRoute,
  WorkerIdRoute: WorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
