/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BomRouteImport } from './routes/bom'
import { Route as HrRouteImport } from './routes/hr'
import { Route as HubsRouteImport } from './routes/hubs'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ProductionTargetsRouteImport } from './routes/production-targets'
import { Route as RawMaterialsRouteImport } from './routes/raw-materials'
import { Route as ShortagesRouteImport } from './routes/shortages'
import { Route as SubhubRouteImport } from './routes/subhub'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as BomCodeRouteImport } from './routes/bom.$code'
import { Route as HubCodeRouteImport } from './routes/hub.$code'
import { Route as InventoryAdjustmentRouteImport } from './routes/inventory.adjustment'
import { Route as InventoryHistoryRouteImport } from './routes/inventory.history'
import { Route as PartCodeRouteImport } from './routes/part.$code'
import { Route as PoIdRouteImport } from './routes/po.$id'
import { Route as SkuCodeRouteImport } from './routes/sku.$code'
import { Route as SubhubBomRouteImport } from './routes/subhub.bom'
import { Route as SubhubFloatParentRouteImport } from './routes/subhub.float-parent'
import { Route as SubhubHrRouteImport } from './routes/subhub.hr'
import { Route as SubhubProductionRouteImport } from './routes/subhub.production'
import { Route as SubhubRawMaterialsRouteImport } from './routes/subhub.raw-materials'
import { Route as SubhubReportsRouteImport } from './routes/subhub.reports'
import { Route as WorkerIdRouteImport } from './routes/worker.$id'
import { Route as SubhubBomCodeRouteImport } from './routes/subhub.bom.$code'
import { Route as SubhubParentCodeRouteImport } from './routes/subhub.parent.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BomRoute = BomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsRoute = HubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionTargetsRoute = ProductionTargetsRouteImport.update({
  id: '/production-targets',
  path: '/production-targets',
  getParentRoute: () => rootRouteImport,
} as any)
const RawMaterialsRoute = RawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortagesRoute = ShortagesRouteImport.update({
  id: '/shortages',
  path: '/shortages',
  getParentRoute: () => rootRouteImport,
} as any)
const SubhubRoute = SubhubRouteImport.update({
  id: '/subhub',
  path: '/subhub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const BomCodeRoute = BomCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => BomRoute,
} as any)
const HubCodeRoute = HubCodeRouteImport.update({
  id: '/hub/$code',
  path: '/hub/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAdjustmentRoute = InventoryAdjustmentRouteImport.update({
  id: '/adjustment',
  path: '/adjustment',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryHistoryRoute = InventoryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InventoryRoute,
} as any)
const PartCodeRoute = PartCodeRouteImport.update({
  id: '/part/$code',
  path: '/part/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PoIdRoute = PoIdRouteImport.update({
  id: '/po/$id',
  path: '/po/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SkuCodeRoute = SkuCodeRouteImport.update({
  id: '/sku/$code',
  path: '/sku/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SubhubBomRoute = SubhubBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubFloatParentRoute = SubhubFloatParentRouteImport.update({
  id: '/float-parent',
  path: '/float-parent',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubHrRoute = SubhubHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubProductionRoute = SubhubProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubRawMaterialsRoute = SubhubRawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => SubhubRoute,
} as any)
const SubhubReportsRoute = SubhubReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SubhubRoute,
} as any)
const WorkerIdRoute = WorkerIdRouteImport.update({
  id: '/worker/$id',
  path: '/worker/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SubhubBomCodeRoute = SubhubBomCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => SubhubBomRoute,
} as any)
const SubhubParentCodeRoute = SubhubParentCodeRouteImport.update({
  id: '/parent/$code',
  path: '/parent/$code',
  getParentRoute: () => SubhubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bom': typeof BomRouteWithChildren
  '/hr': typeof HrRoute
  '/hubs': typeof HubsRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/production-targets': typeof ProductionTargetsRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/shortages': typeof ShortagesRoute
  '/subhub': typeof SubhubRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/bom/$code': typeof BomCodeRoute
  '/hub/$code': typeof HubCodeRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/part/$code': typeof PartCodeRoute
  '/po/$id': typeof PoIdRoute
  '/sku/$code': typeof SkuCodeRoute
  '/subhub/bom': typeof SubhubBomRouteWithChildren
  '/subhub/float-parent': typeof SubhubFloatParentRoute
  '/subhub/hr': typeof SubhubHrRoute
  '/subhub/production': typeof SubhubProductionRoute
  '/subhub/raw-materials': typeof SubhubRawMaterialsRoute
  '/subhub/reports': typeof SubhubReportsRoute
  '/worker/$id': typeof WorkerIdRoute
  '/subhub/bom/$code': typeof SubhubBomCodeRoute
  '/subhub/parent/$code': typeof SubhubParentCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bom': typeof BomRouteWithChildren
  '/hr': typeof HrRoute
  '/hubs': typeof HubsRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/production-targets': typeof ProductionTargetsRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/shortages': typeof ShortagesRoute
  '/subhub': typeof SubhubRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/bom/$code': typeof BomCodeRoute
  '/hub/$code': typeof HubCodeRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/part/$code': typeof PartCodeRoute
  '/po/$id': typeof PoIdRoute
  '/sku/$code': typeof SkuCodeRoute
  '/subhub/bom': typeof SubhubBomRouteWithChildren
  '/subhub/float-parent': typeof SubhubFloatParentRoute
  '/subhub/hr': typeof SubhubHrRoute
  '/subhub/production': typeof SubhubProductionRoute
  '/subhub/raw-materials': typeof SubhubRawMaterialsRoute
  '/subhub/reports': typeof SubhubReportsRoute
  '/worker/$id': typeof WorkerIdRoute
  '/subhub/bom/$code': typeof SubhubBomCodeRoute
  '/subhub/parent/$code': typeof SubhubParentCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bom': typeof BomRouteWithChildren
  '/hr': typeof HrRoute
  '/hubs': typeof HubsRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/procurement': typeof ProcurementRoute
  '/production': typeof ProductionRoute
  '/production-targets': typeof ProductionTargetsRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/shortages': typeof ShortagesRoute
  '/subhub': typeof SubhubRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/bom/$code': typeof BomCodeRoute
  '/hub/$code': typeof HubCodeRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/part/$code': typeof PartCodeRoute
  '/po/$id': typeof PoIdRoute
  '/sku/$code': typeof SkuCodeRoute
  '/subhub/bom': typeof SubhubBomRouteWithChildren
  '/subhub/float-parent': typeof SubhubFloatParentRoute
  '/subhub/hr': typeof SubhubHrRoute
  '/subhub/production': typeof SubhubProductionRoute
  '/subhub/raw-materials': typeof SubhubRawMaterialsRoute
  '/subhub/reports': typeof SubhubReportsRoute
  '/worker/$id': typeof WorkerIdRoute
  '/subhub/bom/$code': typeof SubhubBomCodeRoute
  '/subhub/parent/$code': typeof SubhubParentCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bom'
    | '/hr'
    | '/hubs'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/production'
    | '/production-targets'
    | '/raw-materials'
    | '/shortages'
    | '/subhub'
    | '/admin/users'
    | '/bom/$code'
    | '/hub/$code'
    | '/inventory/adjustment'
    | '/inventory/history'
    | '/part/$code'
    | '/po/$id'
    | '/sku/$code'
    | '/subhub/bom'
    | '/subhub/float-parent'
    | '/subhub/hr'
    | '/subhub/production'
    | '/subhub/raw-materials'
    | '/subhub/reports'
    | '/worker/$id'
    | '/subhub/bom/$code'
    | '/subhub/parent/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bom'
    | '/hr'
    | '/hubs'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/production'
    | '/production-targets'
    | '/raw-materials'
    | '/shortages'
    | '/subhub'
    | '/admin/users'
    | '/bom/$code'
    | '/hub/$code'
    | '/inventory/adjustment'
    | '/inventory/history'
    | '/part/$code'
    | '/po/$id'
    | '/sku/$code'
    | '/subhub/bom'
    | '/subhub/float-parent'
    | '/subhub/hr'
    | '/subhub/production'
    | '/subhub/raw-materials'
    | '/subhub/reports'
    | '/worker/$id'
    | '/subhub/bom/$code'
    | '/subhub/parent/$code'
  id:
    | '__root__'
    | '/'
    | '/bom'
    | '/hr'
    | '/hubs'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/procurement'
    | '/production'
    | '/production-targets'
    | '/raw-materials'
    | '/shortages'
    | '/subhub'
    | '/admin/users'
    | '/bom/$code'
    | '/hub/$code'
    | '/inventory/adjustment'
    | '/inventory/history'
    | '/part/$code'
    | '/po/$id'
    | '/sku/$code'
    | '/subhub/bom'
    | '/subhub/float-parent'
    | '/subhub/hr'
    | '/subhub/production'
    | '/subhub/raw-materials'
    | '/subhub/reports'
    | '/worker/$id'
    | '/subhub/bom/$code'
    | '/subhub/parent/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BomRoute: typeof BomRouteWithChildren
  HrRoute: typeof HrRoute
  HubsRoute: typeof HubsRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProcurementRoute: typeof ProcurementRoute
  ProductionRoute: typeof ProductionRoute
  ProductionTargetsRoute: typeof ProductionTargetsRoute
  RawMaterialsRoute: typeof RawMaterialsRoute
  ShortagesRoute: typeof ShortagesRoute
  SubhubRoute: typeof SubhubRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  HubCodeRoute: typeof HubCodeRoute
  PartCodeRoute: typeof PartCodeRoute
  PoIdRoute: typeof PoIdRoute
  SkuCodeRoute: typeof SkuCodeRoute
  WorkerIdRoute: typeof WorkerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom': {
      id: '/bom'
      path: '/bom'
      fullPath: '/bom'
      preLoaderRoute: typeof BomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs': {
      id: '/hubs'
      path: '/hubs'
      fullPath: '/hubs'
      preLoaderRoute: typeof HubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-targets': {
      id: '/production-targets'
      path: '/production-targets'
      fullPath: '/production-targets'
      preLoaderRoute: typeof ProductionTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-materials': {
      id: '/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof RawMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortages': {
      id: '/shortages'
      path: '/shortages'
      fullPath: '/shortages'
      preLoaderRoute: typeof ShortagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subhub': {
      id: '/subhub'
      path: '/subhub'
      fullPath: '/subhub'
      preLoaderRoute: typeof SubhubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bom/$code': {
      id: '/bom/$code'
      path: '/$code'
      fullPath: '/bom/$code'
      preLoaderRoute: typeof BomCodeRouteImport
      parentRoute: typeof BomRoute
    }
    '/hub/$code': {
      id: '/hub/$code'
      path: '/hub/$code'
      fullPath: '/hub/$code'
      preLoaderRoute: typeof HubCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/adjustment': {
      id: '/inventory/adjustment'
      path: '/adjustment'
      fullPath: '/inventory/adjustment'
      preLoaderRoute: typeof InventoryAdjustmentRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/history': {
      id: '/inventory/history'
      path: '/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof InventoryHistoryRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/part/$code': {
      id: '/part/$code'
      path: '/part/$code'
      fullPath: '/part/$code'
      preLoaderRoute: typeof PartCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po/$id': {
      id: '/po/$id'
      path: '/po/$id'
      fullPath: '/po/$id'
      preLoaderRoute: typeof PoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sku/$code': {
      id: '/sku/$code'
      path: '/sku/$code'
      fullPath: '/sku/$code'
      preLoaderRoute: typeof SkuCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subhub/bom': {
      id: '/subhub/bom'
      path: '/bom'
      fullPath: '/subhub/bom'
      preLoaderRoute: typeof SubhubBomRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/float-parent': {
      id: '/subhub/float-parent'
      path: '/float-parent'
      fullPath: '/subhub/float-parent'
      preLoaderRoute: typeof SubhubFloatParentRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/hr': {
      id: '/subhub/hr'
      path: '/hr'
      fullPath: '/subhub/hr'
      preLoaderRoute: typeof SubhubHrRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/production': {
      id: '/subhub/production'
      path: '/production'
      fullPath: '/subhub/production'
      preLoaderRoute: typeof SubhubProductionRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/raw-materials': {
      id: '/subhub/raw-materials'
      path: '/raw-materials'
      fullPath: '/subhub/raw-materials'
      preLoaderRoute: typeof SubhubRawMaterialsRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/subhub/reports': {
      id: '/subhub/reports'
      path: '/reports'
      fullPath: '/subhub/reports'
      preLoaderRoute: typeof SubhubReportsRouteImport
      parentRoute: typeof SubhubRoute
    }
    '/worker/$id': {
      id: '/worker/$id'
      path: '/worker/$id'
      fullPath: '/worker/$id'
      preLoaderRoute: typeof WorkerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subhub/bom/$code': {
      id: '/subhub/bom/$code'
      path: '/$code'
      fullPath: '/subhub/bom/$code'
      preLoaderRoute: typeof SubhubBomCodeRouteImport
      parentRoute: typeof SubhubBomRoute
    }
    '/subhub/parent/$code': {
      id: '/subhub/parent/$code'
      path: '/parent/$code'
      fullPath: '/subhub/parent/$code'
      preLoaderRoute: typeof SubhubParentCodeRouteImport
      parentRoute: typeof SubhubRoute
    }
  }
}

interface BomRouteChildren {
  BomCodeRoute: typeof BomCodeRoute
}

const BomRouteChildren: BomRouteChildren = {
  BomCodeRoute: BomCodeRoute,
}

const BomRouteWithChildren = BomRoute._addFileChildren(BomRouteChildren)

interface InventoryRouteChildren {
  InventoryAdjustmentRoute: typeof InventoryAdjustmentRoute
  InventoryHistoryRoute: typeof InventoryHistoryRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryAdjustmentRoute: InventoryAdjustmentRoute,
  InventoryHistoryRoute: InventoryHistoryRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface SubhubBomRouteChildren {
  SubhubBomCodeRoute: typeof SubhubBomCodeRoute
}

const SubhubBomRouteChildren: SubhubBomRouteChildren = {
  SubhubBomCodeRoute: SubhubBomCodeRoute,
}

const SubhubBomRouteWithChildren = SubhubBomRoute._addFileChildren(
  SubhubBomRouteChildren,
)

interface SubhubRouteChildren {
  SubhubBomRoute: typeof SubhubBomRouteWithChildren
  SubhubFloatParentRoute: typeof SubhubFloatParentRoute
  SubhubHrRoute: typeof SubhubHrRoute
  SubhubProductionRoute: typeof SubhubProductionRoute
  SubhubRawMaterialsRoute: typeof SubhubRawMaterialsRoute
  SubhubReportsRoute: typeof SubhubReportsRoute
  SubhubParentCodeRoute: typeof SubhubParentCodeRoute
}

const SubhubRouteChildren: SubhubRouteChildren = {
  SubhubBomRoute: SubhubBomRouteWithChildren,
  SubhubFloatParentRoute: SubhubFloatParentRoute,
  SubhubHrRoute: SubhubHrRoute,
  SubhubProductionRoute: SubhubProductionRoute,
  SubhubRawMaterialsRoute: SubhubRawMaterialsRoute,
  SubhubReportsRoute: SubhubReportsRoute,
  SubhubParentCodeRoute: SubhubParentCodeRoute,
}

const SubhubRouteWithChildren =
  SubhubRoute._addFileChildren(SubhubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BomRoute: BomRouteWithChildren,
  HrRoute: HrRoute,
  HubsRoute: HubsRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProcurementRoute: ProcurementRoute,
  ProductionRoute: ProductionRoute,
  ProductionTargetsRoute: ProductionTargetsRoute,
  RawMaterialsRoute: RawMaterialsRoute,
  ShortagesRoute: ShortagesRoute,
  SubhubRoute: SubhubRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  HubCodeRoute: HubCodeRoute,
  PartCodeRoute: PartCodeRoute,
  PoIdRoute: PoIdRoute,
  SkuCodeRoute: SkuCodeRoute,
  WorkerIdRoute: WorkerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
